task: hopper-medium-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
# data_path: "/public/sparse_d4rl/hopper-medium-v2.pkl"
epoch: 1000
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/hopper_normal/kde"
density_model: kde