task: halfcheetah-medium-expert-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
# data_path: "/public/sparse_d4rl/halfcheetah-medium-v2.pkl"
epoch: 1000
rollout-length: 5
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/halfcheetah_medium_expert/kde"
density_model: kde
