_wandb:
    value:
        cli_version: 0.22.2
        e:
            bzq7x8yib2kror0a27slqxivfxpyyjjf:
                args:
                    - --config
                    - configs/halfcheetah_linear.yaml
                    - --devid
                    - "5"
                codePath: mopo.py
                codePathLocal: mopo.py
                cpu_count: 56
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "280746393600"
                        used: "250902872064"
                email: aysintumay@gmail.com
                executable: /home/ubuntu/miniconda3/envs/cormpo/bin/python
                git:
                    commit: 8c567908e8e5c18b595966bdc6a5805adc1b0a7f
                    remote: git@github.com:aysintumay/GORMPO.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-2878cd24-7742-5573-327f-e319d5acc71e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-3ff88106-3d94-ecf4-7797-263d3aa09bb9
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-81da9449-8de2-453b-316d-3fe365fe0073
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-3f8c0419-614b-671f-456b-11abc0e33ff9
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-386b4d8f-29d0-93dc-b6bf-230391545f59
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-d3ee2170-bd7e-a2bc-16f6-b6a31dfddbc2
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-f86453d3-3a09-317a-4975-9a950411a650
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-fcbef5fb-2c28-ee8f-6371-4ff8ce607a73
                host: aysin
                memory:
                    total: "128000000000"
                os: Linux-5.15.0-160-generic-x86_64-with-glibc2.17
                program: mopo.py
                python: CPython 3.8.20
                root: /home/ubuntu/GORMPO
                startedAt: "2025-11-09T22:52:20.499111Z"
                writerId: bzq7x8yib2kror0a27slqxivfxpyyjjf
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.8.20
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
action:
    value: false
actor_lr:
    value: 0.0003
algo_name:
    value: gormpo
alpha:
    value: 0.2
alpha_lr:
    value: 0.0003
auto_alpha:
    value: true
batch_size:
    value: 256
classifier_model_name:
    value: /public/gormpo/models/halfcheetah/realnvp
config:
    value: configs/halfcheetah_linear.yaml
critic_lr:
    value: 0.0003
data_path:
    value: public/sparse_d4rl/hopper-medium-v2.pkl
density_model:
    value: realnvp
device:
    value: cuda
devid:
    value: 5
dynamics_lr:
    value: 0.001
dynamics_model_dir:
    value: null
epoch:
    value: 100
eval_episodes:
    value: 100
gamma:
    value: 0.99
loc:
    value: 0
log_freq:
    value: 1000
logdir:
    value: log
model_path:
    value: ""
model_retain_epochs:
    value: 5
n_elites:
    value: 5
n_ensembles:
    value: 7
noise_rate_action:
    value: 0.01
noise_rate_transition:
    value: 0.01
penalty_type:
    value: linear
policy_path:
    value: ""
real_ratio:
    value: 0.05
reward_penalty_coef:
    value: 0.005
rollout_batch_size:
    value: 50000
rollout_freq:
    value: 1000
rollout_length:
    value: 5
root_dir:
    value: log
scale_action:
    value: 0.001
scale_transition:
    value: 0.001
seed:
    value: 1
seeds:
    value:
        - 1
step_per_epoch:
    value: 1000
target_entropy:
    value: -1
task:
    value: HalfCheetah
tau:
    value: 0.005
terminal_counter:
    value: 1
transition:
    value: false
