task: halfcheetah-medium-v2
algo-name: gormpo
reward-penalty-coef: 0.1
seed: 1
# data_path: "/public/sparse_d4rl/halfcheetah-medium-v2.pkl"
epoch: 1000
penalty_type: 'tanh'
rollourl-length: 5
classifier_model_name: "/public/gormpo/models/halfcheetah_normal/realnvp"

