task: hopper-medium-v2
algo-name: gormpo
reward-penalty-coef: 0.8
seed: 1
# data_path: "/public/sparse_d4rl/hopper-medium-v2.pkl"
epoch: 1000
penalty_type: 'tanh'
rollout-length: 5
classifier_model_name: "/public/gormpo/models/hopper_normal/realnvp"

