task: HalfCheetah
algo-name: gormpo
reward-penalty-coef: 0.005
seed: 1
data_path: "/public/sparse_d4rl/halfcheetah-medium-v2.pkl"
epoch: 100
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/halfcheetah/realnvp"

