task: Hopper
algo-name: gormpo
reward-penalty-coef: 1
seed: 1
data_path: "/public/sparse_d4rl/hopper-medium-v2.pkl"
epoch: 100
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/hopper/realnvp"

