classifier_model_name: /public/gormpo/models/hopper_medium_expert_sparse_3/diffusion/checkpoint.pt
density_model: diffusion

task: hopper-medium-expert-v2
data_path: /public/d4rl/sparse_datasets/hopper_medium_expert_sparse_78.pkl

algo-name: gormpo
reward-penalty-coef: 0.05
seed: 1
epoch: 1000
penalty_type: 'tanh'
rollout-length: 5