classifier_model_name: /public/gormpo/models/walker2d_medium_expert_sparse_3/diffusion/checkpoint.pt
density_model: diffusion

task: walker2d-medium-expert-v2
data_path: /public/d4rl/sparse_datasets/walker2d_medium_expert_sparse_73.pkl

algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
epoch: 1000
penalty_type: 'tanh'
rollout-length: 5