classifier_model_name: /public/gormpo/models/halfcheetah/diffusion/checkpoint.pt
density_model: diffusion

task: halfcheetah-medium-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
# data_path: "/public/sparse_d4rl/hopper-medium-v2.pkl"
epoch: 500
penalty_type: 'tanh'
rollout-length: 1