classifier_model_name: /public/gormpo/models/hopper/diffusion/checkpoint.pt
density_model: diffusion

task: hopper-medium-v2
algo-name: gormpo
reward-penalty-coef: 1
seed: 1
# data_path: "/public/sparse_d4rl/hopper-medium-v2.pkl"
epoch: 100
penalty_type: 'tanh'