classifier_model_name: /public/gormpo/models/walker2d_medium_replay/diffusion/checkpoint.pt
density_model: diffusion

task: walker2d-medium-replay-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
epoch: 1000
penalty_type: 'tanh'
rollout-length: 1