classifier_model_name: /public/gormpo/models/walker2d/diffusion/checkpoint.pt
density_model: diffusion

task: walker2d-medium-v2
algo-name: gormpo
reward-penalty-coef: 1
seed: 1
epoch: 100
penalty_type: 'tanh'