classifier_model_name: /public/gormpo/models/halfcheetah/neuralODE/model.pt
density_model: neuralODE

hidden_dims: [512, 512]
activation: silu
time_dependent: true
solver: dopri5
t0: 0.0
t1: 1.0
rtol: 1.0e-5
atol: 1.0e-5
target_dim: 23

task: halfcheetah-medium-v2
algo-name: gormpo
reward-penalty-coef: 1
seed: 1
# data_path: "/public/sparse_d4rl/hopper-medium-v2.pkl"
epoch: 100
penalty_type: 'tanh'