classifier_model_name: /public/gormpo/models/walker2d_medium_replay/neuralODE
density_model: neuralODE
hidden_dims: [512, 512]
activation: silu
time_dependent: true
solver: dopri5
t0: 0.0
t1: 1.0
rtol: 1.0e-5
atol: 1.0e-5
target_dim: 23

task: walker2d-medium-replay-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
epoch: 1000
rollout-length: 1
penalty_type: 'tanh'