task: hopper-medium-replay-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
# data_path: "/public/sparse_d4rl/hopper-medium-replay-v2.pkl"
epoch: 1000
rollout-length: 5
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/hopper_medium_replay/vae"
density_model: vae
