task: walker2d-medium-expert-v2
algo-name: gormpo
reward-penalty-coef: 0.5
seed: 1
# data_path: "/public/sparse_d4rl/walker2d-medium-v2.pkl"
epoch: 1000
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/walker2d_medium_expert/vae"
density_model: vae