task: walker2d-medium-v2
algo-name: gormpo
reward-penalty-coef: 0.3
seed: 1
# data_path: "/public/sparse_d4rl/walker2d-medium-v2.pkl"
epoch: 1000
rollout-length: 5
penalty_type: 'tanh'
classifier_model_name: "/public/gormpo/models/walker2d_normal/vae"
density_model: vae